### PR TITLE
Updated to capacitor version 4

### PR DESCRIPTION
**Pull request by stephannagel**
I have updated the plugin to capacitor version 4. Have a look what you think :)

### CODE REVIEW

**Comment by boehlerlukas** [comment]
Hey @stephannagel ,

awesome, thanks a lot. I will run a full test by next Monday and then happily merge it into the master.

**Comment by stephannagel** [comment]
@boehlerlukas did you have a change to have a look yet?

**Comment by boehlerlukas** [comment]
Hey @stephannagel ,

sorry for the late reply. Yes :) We are currently in preperation for the widget v8 (which brings in lot's of new amazing features). The beta release will be next week. We'd actually love to already bumb this branch to v8 as soon as the dependencies are available.

**Comment by stephannagel** [comment]
Hey @boehlerlukas, have you had a change yet to have a look at updating it to capacitor 4? People who are using capacitor 4 are no longer able to use this plugin.

**Comment by boehlerlukas** [comment]
@stephannagel thanks for your help - we just merged the current main into the branch and run through some tests. We are ready to take off 🚀

**Pull request merged**
